aitjcize/cppman

README.rst
Hey, when trying to use cppman for the first time I got this error:
```
"/usr/local/lib/python2.7/dist-packages/cppman/main.py", line 35, in <module>import urllib.request
ImportError: No module named request
```
It turns out that `urillib.request` is available for Python 3.x only. It took me a couple of minutes to fix it by uninstalling cppman in re-installing using `pip3`.
I hope that my small enhancement will help feature users to avoid this issue altogether.
=> Add clarification about Python 3 in the readme

cppman/crawler.py
when i went to update the cppman cache i got this `TypeError: can't use a string pattern on a bytes-like object` when it was trying to regexsearch the response data.
anyway as far as I can tell, this tiny change seems to fix it.
duno if this happens for anyone else though.
=> fix `TypeError: can't use a string pattern on a bytes-like object`

bin/cppman
Without that, last line of copyright was merging with $PS1
=> bin: add newline after copyright

cppman/main.py
It's more clear if user input is placed to the right of the prompt, not in the newline
=> main: do not insert extra \n in --cache-all

cppman/formatter/cppreference.py
Includes python 3.7 fix for cppreference.com.
This Code is related to the fix in [1f02c4](https://github.com/aitjcize/cppman/commit/1f02c413feb6f716d429445abc4ad56a94d7f051) which does the same for cplusplus.com.
=> Fix regexp escape for python 3.7 for cppreference.com

cppman/lib/cppman.vim
This makes vim consider the buffer a scratch buffer so you can exit
normally with `:q` even if the buffer changed.
It removes the `[noperm]` indicator as well. I figured vim users are used to exiting with `:q` and it gets annoying to be asked to save changes.
=> VIM PAGER: set buftype=nofile

bin/cppman, cppman/environ.py, cppman/main.py, cppman/util.py, misc/cppman.1
This PR is supposed to fix #45 and both issues in #74 
== Moving Paths
Instead of using ~/.config/cppman and ~/.local/share/man now XDG_* env
variables are being used:
$XDG_CONFIG_HOME/cppman (= ~/.config/cppman)
$XDG_CACHE_HOME/cppman  (= ~/.cache/cppman)
Following things have moved:
~/.config/cppman/cppman.cfg → $XDG_CONFIG_HOME/cppman/cppman.cfg
~/.config/cppman/index.db   → $XDG_CACHE_HOME/cppman/index.db
~/.local/share/man/*        → $XDG_CACHE_HOME/cppman/
== Fix and Extend .manpath
This also adds another entry to "~/.mandb" to allow indexing of man pages
and searching. (need to call mandb to successfully index entries)
Also `cppman -k false` now removes the entries from .manpath
=> moving PATHS and make them dependent on XDG_* env variables

bin/cppman
If one of the search terms can't be found this will return an exit code 1.
Should solve issue #93
=> Different exit code if man page could not be found.

README.rst, misc/completions/cppman.bash, misc/completions/cppman.zsh, setup.py
Feat: add bash and zsh completion files
This adds completions file for bash and zsh.
The setup.py is changed so the files are being installed to
- <root>/share/bash-completion/completions/cppman.bash
- <root>/share/zsh-completion/completions/cppman.zsh
Bash treats ':' as white spaces which makes using bash completion not as
nice as I wished (zsh does not have this issue). This can be fixed for
bash by adding the following line to `~/.bashrc`
```
export COMP_WORDBREAKS=" /\"\'><;|&("
```
=> Feat: add bash and zsh completion files

cppman/lib/cppman.vim, cppman/lib/pager.sh
Fixes issue #92 .
calling `cppman vector" would always leave a "Vim: Reading from
stdin..." message on the command line. This is not pretty.
This commit rewrites how vim is being called fixing this issue.
=> Patch: Change call to vim pager to avoid "reading from stdin"

cppman/main.py
Fixes issue #97 .
cppman -f "C++" didn't work. This adds escape sequences to the search
pattern.
=> Fix: search cppman with regex symbols

.travis.yml, setup.py
relates to https://github.com/Homebrew/homebrew-core/pull/49077 (the formula already shipped with python 3.8)
=> Add python 3.8 and deprecate 3.3 and 3.4

cppman/crawler.py, cppman/main.py
This PR fixes and enhances the crawler which currently looses quite a lot URLs due to network errors. For example, the number of pages in the cppreference.com table increases from 4286 to 5341. Now all failed downloads are collected and retried after a round of crawling. The process continues until either 1) there are no failed downloads or 2) no download progress is seen for a number of rounds (`self.max_failed_retries`).
The PR also fixes the issue with multiple pages having the same title such as [std::move](https://en.cppreference.com/w/cpp/algorithm/move) and [std::move](https://en.cppreference.com/w/cpp/utility/move). In such cases a part of the path is added to the title resulting in `std::move (algorithm)` and `std::move (utility)`. There are 126 such pages (both cplusplus.com and …
=> A more rubust crawler

cppman/crawler.py, cppman/formatter/cplusplus.py, cppman/formatter/cppreference.py, cppman/main.py, cppman/util.py
Looks like cppreference is blocking urllib requests now. This PR fixes it. To test run
PYTHONPATH=. python3 cppman/formatter/cppreference.py
After adding custom headers indexing works much faster. Maybe we should consider slowing it down to put less stress on the sites.
=> Add custom headers to requests

cppman/formatter/cppreference.py
Cut [static] or [virtual] and prepend it to the tail.
Examples to reproduce:
https://en.cppreference.com/w/cpp/error/exception
what [virtual]
cppman 'std::exception'
https://en.cppreference.com/w/cpp/string/basic_string
npos [static]
cppman 'std::basic_string'
=> cppreference.com: fix [static], [virtual]

cppman/main.py
This fixes 'string (2)' vs 'std::to_string(2)' issue (std:: has a higher priority). To reproduce run:
cppman 'string (2)'
=> Prioritize exact matches in search results

cppman/lib/pager.sh
Now pager `less` shows format-styling escape sequence `^Esc` as it is.
Needs `-r` option.
=> Add `-r` option to pager `less` command to follow control chars

bin/cppman
As `man` command, return exit code `16` for not-found case.
=> Change exit code if no entry found

cppman/formatter/cppreference.py, cppman/formatter/tableparser.py, cppman/main.py
Python3.11 and newer versions like to complain about unknown escape sequences like `\.`, `\s` etc.
When you install cppman through a package manager on Linux, you'll see something similar to this:
```
...
cppman-0.5.6_2: configuring ...
Byte-compiling python3.12 code for module cppman...
usr/lib/python3.12/site-packages/cppman/formatter/cppreference.py:47: SyntaxWarning: invalid escape sequence '\['
'^(.*?)(\[(?:(?:since|until) )?C\+\+\d+\]\s*(,\s*)?)+$', head)
usr/lib/python3.12/site-packages/cppman/formatter/cppreference.py:115: SyntaxWarning: invalid escape sequence '\s'
lambda x: re.sub('\s*</span><span>\s*', r', ', x.group(0)), re.S),
usr/lib/python3.12/site-packages/cppman/formatter/tableparser.py:147: SyntaxWarning: invalid escape sequence '\^'
fd.write('\^%s' % ('|' if i < total - …
```
=> Properly escape regex string literals

cppman/lib/pager.sh
This PR adds the command line argument `--cmd "let g:is_cppman_active=1"` in `pager.sh` when using `vim` or `nvim` as a pager.
This is useful, because commands provided with `--cmd` are processed before any vimrc file is processed (see manpage for vim/nvim), which means the user can check in their `init.lua` or `init.vim` file if the current vim instance has been launched by `cppman` (by checking the value of `is_cppman_active`) and can therefore choose to omit certain configurations or abstain from loading some plugins.
=> global vim variable 'is_cppman_active'

cppman/main.py
SQLite LIKE operator is case-insensitive. Hence the replacement must be case-insensitive too. If it is not, the keyword found by LIKE might not be replaced and will be found again and again. That will cause unlimited growth of sql_results.
Example:
https://en.cppreference.com/w/cpp/memory/allocator and Allocator  template argument
Another option would be using GLOB instead of LIKE for case-sensitive search. Whether it is better or not and search pattern selection is out of scope of this commit.
=> Fix alias insertion
